name: iOS CI/CD
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    name: Build and Test on Xcode
    runs-on: macos-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Xcode version
      uses: maxim-lobanov/setup-xcode@v1.2.1
      with:
        xcode-version: 'latest-stable' # 或者指定具体版本，如 '13.0'
 
    - name: Build Project
      run: |
        xcodebuild clean build -project YourProject.xcodeproj -scheme YourScheme -destination 'platform=iOS Simulator,name=iPhone 13' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - name: Run Tests
      run: |
        xcodebuild test -project YourProject.xcodeproj -scheme YourScheme -destination 'platform=iOS Simulator,name=iPhone 13' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES
        xcrun xcodebuild -exportArchive -archivePath YourArchive.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath YourExportPath
    
    # 可以添加额外的步骤，如部署到 TestFlight 或 App Store Connect 等
